### ISSUE TITLE
Allow connection via Session Manager

### ISSUE THREAD

**Issue by avishayil** [avishayil/secure_ec2#4]
### Description

Implement some kind of wrapper over the session manager plugins to allow easy connection to the EC2 instance via the AWS console or the AWS CLI

### Relevant Resources:
- https://docs.aws.amazon.com/systems-manager/latest/userguide/session-manager-working-with-install-plugin.html
- https://github.com/xen0l/aws-gate
- https://docs.aws.amazon.com/systems-manager/latest/userguide/session-manager-working-with-sessions-start.html

**Comment by avishayil** [comment]
One way of implementing this could be with a simple link from the AWS Console. For example:
- Direct link to session manager - https://us-east-1.console.aws.amazon.com/systems-manager/session-manager/i-0ffe6b9bcc655578f?region=us-east-1

**Comment by xee5ch** [comment]
So we were talking on social media and I think I was the one who brought this up. Thanks for adding this preemptively.

I would love the option of doing [web] console or the SSH plugin on the CLI, both great options! If you want, I am willing to help on this one, just give a holler!

**Comment by avishayil** [comment]
Yup! starting to work on this already. I'm also implementing both printing the URL and copying it automatically to the clipboard for easier access even if the user is not logged in to the AWS console.

**Comment by avishayil** [comment]
Referencing #7

**Comment by avishayil** [comment]
solved with #7
